Improve Sample: java security usage
SAP/cloud-security-xsuaa-integration pull request #411
Opened 2020-11-03 14:32 UTC by nenaraab

2020-11-06 14:00 UTC, liga-oz requested changes
just rename the argument, everything else is awesome!

2020-11-09 17:36 UTC, nenaraab commented on samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/HelloJavaServlet.java
> +	private static Logger LOGGER = LoggerFactory.getLogger(HelloJavaServlet.class);
Static logger references should be in Capital cases

2020-11-10 13:59 UTC, nenaraab commented
HI @liga-oz can you please perform another review? The parameter change is applied.

2020-11-10 14:30 UTC, liga-oz approved these changes
@nenaraab all looks good, just please check if the logger in servlet class can also be final.

2020-11-10 14:30 UTC, liga-oz commented on samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/HelloJavaServlet.java
> +	private static Logger LOGGER = LoggerFactory.getLogger(HelloJavaServlet.class);
i guess logger could also be final?

2020-11-10 14:30 UTC, liga-oz commented on samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/XsuaaSecurityFilter.java
> +	public static void sendUnauthorizedResponse(ServletResponse response, String missingScope)  {
missing scope looks really good here

2020-11-10 16:18 UTC, nenaraab commented on samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/HelloJavaServlet.java
> +	private static Logger LOGGER = LoggerFactory.getLogger(HelloJavaServlet.class);
yes. Good idea.

2020-11-10 16:18 UTC, merged