[java-security] Support Custom domain using `ias_iss` claim
SAP/cloud-security-xsuaa-integration pull request #540
Opened 2021-06-18 10:50 UTC by nenaraab

2021-06-21 17:37 UTC, liga-oz requested changes
just a few unclarities, other than that looks fine 😉

2021-06-21 17:37 UTC, liga-oz commented on java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java
> +		String ias_issuer_url = token.getClaimAsString(IAS_ISSUER);
Is there a reason why you don't use camel case for a local variable?

2021-06-21 17:37 UTC, liga-oz commented on java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java
>  	 * private static String getSubdomain(URI uri) { String host = uri.getHost();
what's this private static in javadoc?

2021-06-21 17:37 UTC, liga-oz commented on java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java
>  	 * Creates instance of Issuer validation using the domain.
I think this javadoc does not match the method anymore.

2021-06-21 17:37 UTC, liga-oz commented on java-security/src/test/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidatorTest.java
> +	public void validationFails_whenIssuerIsNull() {
just a suggestion, maybe use Parameterized Tests here, seems that you have a pattern for tests that could be parameterized like [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/9713812ddbc8cb353188725b9067a651eb252952/spring-xsuaa/src/test/java/com/sap/cloud/security/xsuaa/token/XsuaaTokenTest.java#L100)?

2021-06-22 13:55 UTC, nenaraab commented on java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java
>  	 * private static String getSubdomain(URI uri) { String host = uri.getHost();
oh my gosh 💯

2021-06-22 15:20 UTC, merged