improve debug logging #608
SAP/cloud-security-xsuaa-integration pull request #620
Opened 2021-08-12 14:54 UTC by liga-oz

Fixes #608

2021-08-16 16:28 UTC, nenaraab requested changes
Hi @liga-oz 
I would suggest to add some logs on a central place such as 
Base64JwtDecoder.getInstance().decode() instead of "consumer side".

Alternatively we can log the initial 20 characters of the provided jwtToken within HybridTokenFactory implementation in error case.

2021-08-16 16:28 UTC, nenaraab commented on java-security/src/main/java/com/sap/cloud/security/token/AbstractToken.java
> +		LOGGER.debug("Decoded Jwt: HEADER - {}, PAYLOAD - {}, SIGNATURE - {}", decodedJwt.getHeader(), decodedJwt.getPayload(), decodedJwt.getSignature());
there is already a similar implementation available in Base64JwtDecoder.DecodedJwtImpl.toString() - maybe it can be reused / enhanced?

2021-08-16 16:28 UTC, nenaraab commented on java-security/src/main/java/com/sap/cloud/security/servlet/XsuaaTokenAuthenticator.java
> +			LOGGER.debug("Authorization header: {}", authorizationHeader);
unfortunately we can't add the encoded jwt into the log, someone could make use of it (until it gets expired).... If its helpful we could print the first 20 characters sth like "bearer abcdefg123456..."

2021-08-17 13:47 UTC, liga-oz commented
> Hi @liga-oz
> I would suggest to add some logs on a central place such as
> Base64JwtDecoder.getInstance().decode() instead of "consumer side".
> 
> Alternatively we can log the initial 20 characters of the provided jwtToken within HybridTokenFactory implementation in error case.

@nenaraab I don't think HybridTokenFactory would be a handy place to implement that as I would need to catch and rethrow the error again, because errors are caught and handled in Authenticators.

2021-08-17 15:11 UTC, nenaraab requested changes

2021-08-17 16:46 UTC, nenaraab commented on java-security/src/main/java/com/sap/cloud/security/servlet/HybridTokenFactory.java
> +			LOGGER.error("Issue with Jwt parsing. Authorization header: {} - {}", jwtToken.substring(0, 20), e.getMessage());
this log isn't required, when you raise a new exception with that message. 
sth like:
````
String message = "Issue with Jwt parsing. Authorization header: {} - {}", jwtToken.substring(0, 20), e.getMessage()
throw new JsonParsingException(message, e);
````

2021-08-18 08:24 UTC, nenaraab approved these changes

2021-08-18 08:25 UTC, merged