Introduce slim BOM
SAP/cloud-security-xsuaa-integration pull request #742
Opened 2021-12-03 14:58 UTC by liga-oz

closes #635

@nenaraab please check if <distributionManagement> part is required in this BOM

2021-12-06 10:31 UTC, nenaraab requested changes

2021-12-06 10:31 UTC, nenaraab commented on BOM/pom.xml
> +    <groupId>com.sap.cloud.security.xsuaa</groupId>
pls remove xsuaa from groupId

2021-12-06 10:31 UTC, nenaraab commented on BOM/pom.xml
> +        <url>http://github.com/SAP/cloud-security-xsuaa-integration/tree/master</url>
change to main

2021-12-06 10:31 UTC, nenaraab commented on BOM/pom.xml
> +    <distributionManagement>
this part can be removed

2021-12-06 10:31 UTC, nenaraab commented on BOM/pom.xml
> +            <groupId>com.sap.cloud.security.xsuaa</groupId>
no group id specified

2021-12-06 10:31 UTC, nenaraab commented on BOM/pom.xml
> +            <groupId>${parent-groupId}</groupId>
pls double check all group Ids java-security, spring-security and some others have no xsuaa suffix....

2021-12-08 16:59 UTC, nenaraab requested changes

2021-12-08 16:59 UTC, nenaraab commented on bom/pom.xml
> +                <groupId>${xsuaa-groupId}</groupId>
This is the only finding I have: please remove the both `spring-xsuaa-it` and `java-security-it` dependencies from here... 👍

2021-12-08 17:14 UTC, nenaraab commented on bom/pom.xml
> +                <groupId>${xsuaa-groupId}</groupId>
done

2021-12-08 17:26 UTC, nenaraab approved these changes

2021-12-08 17:27 UTC, merged

2021-12-09 08:23 UTC, BraunMatthias commented
Great! This will help a lot to avoid version conflicts.